# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo Installing dependencies...
    pip install robotframework robotframework-seleniumlibrary && npm install chromedriver
  displayName: 'Install dependencies'

- script: |
    echo Running tests...
    timestamp=$(date +%Y%m%d%H%M%S)
    echo "##vso[task.setvariable variable=log_folder;]logs_$timestamp"
    mkdir logs_$timestamp
    robot -d logs_$timestamp/ tests/
  displayName: 'Run Robot Framework tests'
  continueOnError: true
  
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(log_folder)' 
    artifactName: 'RobotFrameworkLogs'
