# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo Installing dependencies...
    pip install robotframework robotframework-seleniumlibrary
  displayName: 'Install dependencies'

- script: |
    echo Running tests...
    robot -d logs/ tests/
  displayName: 'Run Robot Framework tests'
